export const categoryData = [
    { name: "Any Category", id: "imran", img: "" },
    { name: "General Knowledge", id: "9", img: "" },
    { name: "Entertainment: Film", id: "10", img: "" },
    { name: "Entertainment: Music", id: "11", img: "" },
    { name: "Entertainment: Television", id: "13", img: "" },
    { name: "Entertainment: Video Games", id: "14", img: "" },
    { name: "Entertainment: Board Games", id: "15", img: "" },
    { name: "Science & Nature", id: "16", img: "" },
    { name: "Science: Computers", id: "17", img: "" },
    { name: "Science: Mathematics", id: "18", img: "" },
    { name: "Mythology", id: "19", img: "" },
    { name: "Sports", id: "20", img: "" },
    { name: "Geography", id: "21", img: "" },
    { name: "History", id: "22", img: "" },
    { name: "Politics", id: "23", img: "" },
    { name: "Art", id: "24", img: "" },
    { name: "Celebrities", id: "25", img: "" },
    { name: "Animals", id: "26", img: "" },
    { name: "Vehicles", id: "27", img: "" },
    { name: "Entertainment: Comics", id: "28", img: "" },
    { name: "Science: Gadgets", id: "29", img: "" },
  ];